# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 21.4b0
  hooks:
    - id: black
      language_version: python3
      args: ['--check']
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.1
  hooks:
    - id: flake8
